services:
  waha:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - WAHA_BASE_URL=https://gerenciador-whatsapp-wahaa.8rhgjf.easypanel.host
      - WHATSAPP_API_KEY=admin
      - WAHA_DASHBOARD_USERNAME=admin
      - WAHA_DASHBOARD_PASSWORD=admin
      - WHATSAPP_SWAGGER_USERNAME=admin
      - WHATSAPP_SWAGGER_PASSWORD=admin
      - TZ=America/Sao_Paulo
      - WAHA_LOG_FORMAT=JSON
      - WAHA_LOG_LEVEL=info
      - WHATSAPP_DEFAULT_ENGINE=WEBJS
      - WAHA_PRINT_QR=False
      - WAHA_MEDIA_STORAGE=LOCAL
      - WHATSAPP_FILES_FOLDER=/app/.media
      - WHATSAPP_FILES_LIFETIME=0
    volumes:
      - ./sessions:/app/sessions
      - ./.media:/app/.media
    restart: unless-stopped
